//! **This module should never be consumed directly.** The ABI used to communicate
//! between the preflight runner and the avionics.
//!
//! This module's contents are only made public for use by code generated by the
//! [`avionics_harness`](macro@crate::avionics_harness) macro

use core::panic::PanicInfo;

use crate::{Avionics, Control, Sensors};

/// Callback that is called when the driven avionics panics.
///
/// This callback exists to give the user more information about the state of
/// their avionics at the site of the panic. Panics in avionics should be avoided
/// at all costs, since there is no way to safely recover from them
pub type PanicCallback = fn(panic_info: &PanicInfo, avionics_state: &dyn Avionics);

/// Function exposed to the preflight runner that can set the [`PanicCallback`]
pub type SetPanicCallback = fn(callback: PanicCallback);

/// The entry point into the user's avionics
pub type AvionicsGuide = fn(sensors: &Sensors) -> Option<Control>;
