[package]
name = "sim"
version = "0.1.0"
authors = ["Zachary Kohnen <14093962+DusterTheFirst@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.23.0"
nphysics3d = "0.18.0"
ncollide3d = "0.26.1"
log = "0.4.11"
pretty_env_logger = "0.4.0"
dotenv = "0.15.0"
kiss3d = { version = "0.27.0", features = ["conrod"] }
chrono = "0.4.19"
