[package]
name = "fly_example"
version = "0.1.0"
authors = ["Zachary Kohnen <14093962+DusterTheFirst@users.noreply.github.com>"]
edition = "2018"

[lib]
crate-type = [
    "dylib",
    "staticlib",
]

[dependencies]
