on: [push, pull_request]

name: CI

jobs:
  doc:
    name: Build Documentation
    runs-on: ubuntu-latest
    needs: clippy
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: Swatinem/rust-cache@v1

      - uses: actions/checkout@v2

      - uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --release --all-features

      - run: echo "<meta http-equiv=\"refresh\" content=\"0; url=https://dusterthefirst.github.io/preflight/preflight\" />" > target/doc/index.html
      
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: docs
          build_dir: target/doc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Install minimal stable with clippy
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy

      - uses: Swatinem/rust-cache@v1

      - uses: actions/checkout@v2

      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Install minimal stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - uses: Swatinem/rust-cache@v1

      - uses: actions/checkout@v2

      - uses: actions-rs/cargo@v1
        with:
          command: test

  rustfmt:
    name: Rust Format
    runs-on: ubuntu-latest
    steps:
      - name: Install minimal stable with clippy
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt

      - uses: Swatinem/rust-cache@v1

      - uses: actions/checkout@v2

      - name: rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
